In [4]:
import torch
import numpy as np

### Initializing a Tensor

In [2]:
#Directly from Data
data = [[1, 2], [3, 4]]
tensor_data = torch.tensor(data)

In [3]:
tensor_data

tensor([[1, 2],
        [3, 4]])

In [5]:
# From a numpy array
np_array = np.array(data)
tensor_np = torch.from_numpy(np_array)
tensor_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [6]:
type(data)

list

In [7]:
type(tensor_data)

torch.Tensor

In [8]:
type(tensor_np)

torch.Tensor

In [10]:
# From another tensor
"""
In this case, the new tensor takes on the datatype and the shape of the augmented data.
Those methods end with _like
"""

x_ones = torch.ones_like(tensor_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(tensor_data, dtype=torch.float)    # You can explicitly change the datatype of the output data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6027, 0.8321],
        [0.7118, 0.6029]]) 



In [12]:
# With random or constant values
"""
    You can also generate random or constant of any defined shape
"""
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9736, 0.9135, 0.5466],
        [0.8196, 0.3768, 0.9997]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


###  Attributes of a Tensor

In [14]:
# Attributes of a Tensor
"""
    You can know the attributes of a tensor 
"""
tensor = torch.rand(4,6)

print(f"Random Tensor: \n {tensor} \n")
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Random Tensor: 
 tensor([[0.0696, 0.2692, 0.6209, 0.4920, 0.9534, 0.8796],
        [0.3083, 0.5643, 0.5334, 0.8294, 0.2133, 0.7177],
        [0.0710, 0.2764, 0.9913, 0.5792, 0.7153, 0.3500],
        [0.9031, 0.8311, 0.0100, 0.9639, 0.3960, 0.4438]]) 

Shape of tensor: torch.Size([4, 6])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Operations on Tensors

`There are several operations that can be performed on tensors. Including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling, etc.`

In [16]:
# Moving the operations to GPU if it is available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print("Now running on GPU.......")

Now running on GPU.......


In [21]:
# Standard numpy-like indexing and slicing

tensy = torch.ones(6, 6)
 
tensy[5] = 4 # Set the last row to 5
tensy[:, 2:4] = 3 # Set the third and fourth colums to 3
tensy[..., -1] = 0 # Set the last column to zeros
print("First Row: ", tensy[0])
print("First Column: ", tensy[:,0])
print("Last Row: ", tensy[-1])
print("Last column: ", tensy[:, -1])
print(tensy)

First Row:  tensor([1., 1., 3., 3., 1., 0.])
First Column:  tensor([1., 1., 1., 1., 1., 4.])
Last Row:  tensor([4., 4., 3., 3., 4., 0.])
Last column:  tensor([0., 0., 0., 0., 0., 0.])
tensor([[1., 1., 3., 3., 1., 0.],
        [1., 1., 3., 3., 1., 0.],
        [1., 1., 3., 3., 1., 0.],
        [1., 1., 3., 3., 1., 0.],
        [1., 1., 3., 3., 1., 0.],
        [4., 4., 3., 3., 4., 0.]])


In [ ]:
# Joining Tensors

"""
    You can use torch.cat and torch.stack to concatenate a sequence of tensors
"""

"""
    By setting dim=1, the matrices are joined row by row so the row number remains the same.
"""
t1 = torch.cat([tensy, tensy, tensy, tensy], dim=1)
print(f"The output is: \n {t1} \n")


"""
    By setting dim=0, the matrices will be joined column to column therefore the column number remains the same. 
"""
t2 = torch.cat([tensy, tensy, tensy, tensy], dim=0)
print(f"The output is: \n {t2} \n")


# Stacking
"""
    This will create an array of matrices
"""
x1 = torch.stack([tensy, tensy, tensy, tensy], dim=0)
print(f"The output of stack is: \n {x1} \n")

x2 = torch.stack([tensy, tensy, tensy, tensy], dim=1)
print(f"The output of stack is: \n {x2} \n")



`Arithmetic Operations`

In [32]:
#Using the @ operator for matrix multiplication

a = torch.tensor([[2, 1], [1, 2]])
b = torch.tensor([[5, 3, 1],[3, 5, 1]])
c = a @ b
print(f"a: {a}")
print(f"b: {b}")
print(f"c: {c}")

a: tensor([[2, 1],
        [1, 2]])
b: tensor([[5, 3, 1],
        [3, 5, 1]])
c: tensor([[13, 11,  3],
        [11, 13,  3]])


In [34]:
# Using the matmul method for matrix multiplication

a = torch.tensor([[2, 1], [1, 2]])
b = torch.tensor([[5, 3, 1],[3, 5, 1]])
c = torch.matmul(a, b)

print(f"a: {a}")
print(f"b: {b}")
print(f"c: {c}")

a: tensor([[2, 1],
        [1, 2]])
b: tensor([[5, 3, 1],
        [3, 5, 1]])
c: tensor([[13, 11,  3],
        [11, 13,  3]])


In [36]:
# Using the * for element wise multiplication

"""
    This is only feasible if the matrices have the same dimensions
"""

a = torch.tensor([[2, 1], [1, 2]])
b = torch.tensor([[5, 3],[3, 5]])
c = torch.mul(a, b)

print(f"a: {a}")
print(f"b: {b}")
print(f"c: {c}")

a: tensor([[2, 1],
        [1, 2]])
b: tensor([[5, 3],
        [3, 5]])
c: tensor([[10,  3],
        [ 3, 10]])


In [49]:
# Using the mul for element wise multiplication

"""
    This is only feasible if the matrices have the same dimensions
"""

a = torch.tensor([[2, 1], [1, 2]], dtype=torch.float)
b = torch.tensor([[5, 3],[3, 5]], dtype=torch.float)
c = torch.mul(a, b)

print(f"a: {a}")
print(f"b: {b}")
print(f"c: {c}")

a: tensor([[2., 1.],
        [1., 2.]])
b: tensor([[5., 3.],
        [3., 5.]])
c: tensor([[10.,  3.],
        [ 3., 10.]])


In [51]:
# The .item() function coverts a tensor scalar to a numpy scalar
meany = torch.mean(c)
mean_num = torch.mean(c).item()

print(meany)
print(f"meany is of type: {type(meany)}")
print(mean_num)
print(f"mean_num is of type: {type(mean_num)}")

tensor(6.5000)
meany is of type: <class 'torch.Tensor'>
6.5
mean_num is of type: <class 'float'>


In [50]:

torch.mean(c)

tensor(6.5000)

### Brigde with NumPy

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other

In [52]:
tensor = tensor.to('cpu')

`Tensor to NumPy Array`

In [53]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [54]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


`NumPy Array to Tensor`

In [56]:
n = np.ones(5)
t = torch.from_numpy(n)   # converts numpy array to a tensor
print(f"n: {n}")
print(f"t: {t}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [57]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
